version: 2.1

executors:
  go-executor:
    docker:
      - image: circleci/golang:1.14.0
    working_directory: ~/repo

jobs:
  test:
    executor: go-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /go/pkg/mod
            - ~/repo
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports
  after_test:
    executor: go-executor
    steps:
      - restore_cache:
          keys:
            - go-mod-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: see wd
          command: pwd
      - run:
          name: see ls
          command: ls

workflows:
  version: 2
  build:
    jobs:
      - test
      - after_test:
          requires:
            - test