# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  go-executor:
    docker:
      - image: circleci/golang:1.14.0
    working_directory: ~/repo


jobs:
  checkout_code:
    executor: go-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - "/go/pkg/mod"
  test:
    executor: go-executor
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports

workflows:
  version: 2
  checkout_and_test:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
